### ISSUE TITLE
binding model with controller/view

### ISSUE THREAD

**Issue by veggiemonk** [cnatis/generator-mithril-webpack#3]
Hi @cnatis,

Congratulations on this wonderful generator! It's the first time I actually see yeoman working for a project and I can use it :wink: 

Regarding the structure of the app, I find it really nice and consistent. I was wondering if you could share some explanation about why put everything into separate files. I am really interested because I found myself editing the wrong index.js or view.js a few times just because they were open in my editor. So if you could share some of your workflow and your app architecture, I would be grateful.

Thanks and great work!

**Comment by cnatis** [comment]
Hi @veggiemonk,

I don't want to be a stickler and I definitely want to encourage more conversations like this, however I feel that since this isn't an issue with the generator but more of a question, I feel it is better suited to our [Google group](https://groups.google.com/forum/#!forum/yeoman-mithril-webpack-generator). I know its empty currently but the project is new and the community is just starting to bud.

However that being said I would like to answer your question here for your reference. I have chosen to separate the files as this is what @lhorie (Author of Mithril) suggests in his [article on best partices](https://lhorie.github.io/mithril/practices.html#file-separation). However I took it a step further to bring the file separation into a more ES6 friendly format. For instance you should never really need to edit the [index.js file](https://github.com/cnatis/generator-mithril-webpack/blob/master/generators/component/templates/component/index.js) inside a component/module. The index.js file is there to wrap the individual files into a Mithril module/component and allow the module/component be imported via ES6 import and then routed via the Mithril router.

For instance you can import a module/component like so and then route to it with one line.

```
import myModule from './myModule';
m.route(document.body, '/', {
    '/': myModule
});
```

Without the index.js file you would have to import and route modules like so.

```
import myModuleCtrl from './myModule/controller.js';
import myModuleView from './myModule/view.js';
m.route(document.body, '/', {
    '/': {
        controller: myModuleCtrl,
        view, myModuleView
    }
});
```

I highly recommend any user that plans to use with this generator read up on [ES6 module syntax](http://www.2ality.com/2014/09/es6-modules-final.html) and [ES6 class syntax](http://www.2ality.com/2015/02/es6-classes-final.html) as this generator encourages the user to use these features and WebPack allows us to transpile back to ES5 until ES6 is widely supported.

The rest is just plain old JavaScript and the API provided by Mithril.

I have made a [post in the Google group for this question](https://groups.google.com/forum/#!topic/yeoman-mithril-webpack-generator/T_5YpFCu5v8).

P.S. There is a [Wiki page about this topic](https://github.com/cnatis/generator-mithril-webpack/wiki/Application-Structure), currently it leaves much to be desired in the content department, however I will fill it out as soon as possible. Contributors are welcome and have full edit access to the Wiki.
